### ISSUE TITLE
Non responsive site

### ISSUE THREAD

**Issue by yadavravi123** [vyomaaverse/ReLoud#13]
On using the site on small sized screens it is not adjusting it's contents.

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue. :)

**Comment by vyomaaverse** [comment]
> Hey, I would like to help with this issue. :)

Sure, go ahead @abitsalihu

**Comment by vyomaaverse** [comment]
@abitsalihu you still on it?

**Comment by vyomaaverse** [comment]
closed by #13

**Comment by vyomaaverse** [comment]
closed by #17
